/*
 * fluxvideotex.c — GStreamer BaseTransform element: fluxvideotex
 *
 * FLUX Protocol Spec v0.6.3 §16
 *   Resolves video_texture_bindings and flux:// image URIs, composites
 *   multi-channel bindings, uploads GPU textures (OpenGL / Vulkan).
 *
 * poc003 single-channel path:
 *   sink: video/x-raw, format=RGBA  (from videotestsrc via videoconvert)
 *   src : video/x-raw, format=RGBA  (rendered cube, to osxvideosink)
 *
 * Each incoming frame is uploaded as a Filament Texture onto all 6 faces of
 * a unit cube.  The cube rotates slowly on three axes (configurable periods)
 * to demonstrate the live-texture compositing core of fluxvideotex.
 */

#include "fluxvideotex.h"
#include "filament_scene.h"

/* Embedded GLB cube asset — generated by CMake: gen_cube.py → xxd -i */
#include "cube_glb.h"   /* uint8_t assets_cube_glb[]; unsigned int assets_cube_glb_len; */

#include <gst/gst.h>
#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#ifndef PACKAGE
#define PACKAGE "gst-fluxvideotex"
#endif

GST_DEBUG_CATEGORY_STATIC(flux_videotex_debug);
#define GST_CAT_DEFAULT flux_videotex_debug

/* ── Property IDs ────────────────────────────────────────────────────────── */
enum {
    PROP_0,
    PROP_WIDTH,
    PROP_HEIGHT,
    PROP_PERIOD_X,
    PROP_PERIOD_Y,
    PROP_PERIOD_Z,
    PROP_COLOR_SPACE,
    PROP_YCBCR_OUTPUT,
    PROP_GLB_FILE,
};

/* ── GEnum type for FluxColorSpaceMode ───────────────────────────────────── */
GType flux_color_space_mode_get_type(void)
{
    static GType type = 0;
    if (g_once_init_enter(&type)) {
        static const GEnumValue values[] = {
            { FLUX_CS_SRGB,           "FLUX_CS_SRGB",           "srgb"           },
            { FLUX_CS_BT709,          "FLUX_CS_BT709",          "bt709"          },
            { FLUX_CS_REC709_LINEAR,  "FLUX_CS_REC709_LINEAR",  "rec709-linear"  },
            { FLUX_CS_REC2020_LINEAR, "FLUX_CS_REC2020_LINEAR", "rec2020-linear" },
            { FLUX_CS_REC2020_PQ,     "FLUX_CS_REC2020_PQ",     "rec2020-pq"     },
            { FLUX_CS_REC2020_HLG,    "FLUX_CS_REC2020_HLG",    "rec2020-hlg"    },
            { 0, NULL, NULL }
        };
        GType t = g_enum_register_static("FluxColorSpaceMode", values);
        g_once_init_leave(&type, t);
    }
    return type;
}

/* ── Pad templates ───────────────────────────────────────────────────────── */
static GstStaticPadTemplate sink_template = GST_STATIC_PAD_TEMPLATE(
    "sink",
    GST_PAD_SINK,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS(
        "video/x-raw, "
        "format = (string) RGBA, "
        "width  = " GST_VIDEO_SIZE_RANGE ", "
        "height = " GST_VIDEO_SIZE_RANGE ", "
        "framerate = " GST_VIDEO_FPS_RANGE
    )
);

static GstStaticPadTemplate src_template = GST_STATIC_PAD_TEMPLATE(
    "src",
    GST_PAD_SRC,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS(
        "video/x-raw, "
        "format = (string) { RGBA, AYUV }, "
        "width  = " GST_VIDEO_SIZE_RANGE ", "
        "height = " GST_VIDEO_SIZE_RANGE ", "
        "framerate = " GST_VIDEO_FPS_RANGE
    )
);

/* ── GObject boilerplate ─────────────────────────────────────────────────── */
#define flux_videotex_parent_class parent_class
G_DEFINE_TYPE(FluxVideotex, flux_videotex, GST_TYPE_BASE_TRANSFORM)

/* ── Forward declarations ────────────────────────────────────────────────── */
static void          flux_videotex_set_property(GObject*, guint, const GValue*, GParamSpec*);
static void          flux_videotex_get_property(GObject*, guint, GValue*, GParamSpec*);
static void          flux_videotex_finalize(GObject*);
static GstCaps*      flux_videotex_transform_caps(GstBaseTransform*, GstPadDirection,
                                                  GstCaps*, GstCaps*);
static gboolean      flux_videotex_set_caps(GstBaseTransform*, GstCaps*, GstCaps*);
static gboolean      flux_videotex_get_unit_size(GstBaseTransform*, GstCaps*, gsize*);
static GstFlowReturn flux_videotex_transform(GstBaseTransform*, GstBuffer*, GstBuffer*);

/* ── Class init ──────────────────────────────────────────────────────────── */
static void flux_videotex_class_init(FluxVideotexClass* klass)
{
    GObjectClass*         gobject_class   = G_OBJECT_CLASS(klass);
    GstElementClass*      element_class   = GST_ELEMENT_CLASS(klass);
    GstBaseTransformClass* bt_class       = GST_BASE_TRANSFORM_CLASS(klass);

    GST_DEBUG_CATEGORY_INIT(flux_videotex_debug, "fluxvideotex", 0,
                            "FLUX video-texture element");

    gobject_class->set_property = flux_videotex_set_property;
    gobject_class->get_property = flux_videotex_get_property;
    gobject_class->finalize     = flux_videotex_finalize;

    g_object_class_install_property(gobject_class, PROP_WIDTH,
        g_param_spec_uint("width", "Output Width",
            "Rendered output width in pixels",
            1, 16384, 1280,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    g_object_class_install_property(gobject_class, PROP_HEIGHT,
        g_param_spec_uint("height", "Output Height",
            "Rendered output height in pixels",
            1, 16384, 720,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    g_object_class_install_property(gobject_class, PROP_PERIOD_X,
        g_param_spec_double("rotation-period-x", "Rotation Period X",
            "Seconds for one full X-axis rotation",
            1.0, 3600.0, 150.0,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    g_object_class_install_property(gobject_class, PROP_PERIOD_Y,
        g_param_spec_double("rotation-period-y", "Rotation Period Y",
            "Seconds for one full Y-axis rotation",
            1.0, 3600.0, 200.0,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    g_object_class_install_property(gobject_class, PROP_PERIOD_Z,
        g_param_spec_double("rotation-period-z", "Rotation Period Z",
            "Seconds for one full Z-axis rotation",
            1.0, 3600.0, 300.0,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    g_object_class_install_property(gobject_class, PROP_COLOR_SPACE,
        g_param_spec_enum("color-space", "Output Color Space",
            "Output color space for Filament ColorGrading post-processing "
            "(srgb, bt709, rec709-linear, rec2020-linear, rec2020-pq, rec2020-hlg)",
            FLUX_TYPE_COLOR_SPACE_MODE,
            FLUX_CS_SRGB,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    g_object_class_install_property(gobject_class, PROP_YCBCR_OUTPUT,
        g_param_spec_boolean("ycbcr-output", "Y'CbCr Output",
            "Encode the color-graded output as packed Y'CbCr (R=Y', G=Cb, B=Cr, A=1). "
            "When enabled the src pad emits AYUV instead of RGBA.",
            FALSE,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    g_object_class_install_property(gobject_class, PROP_GLB_FILE,
        g_param_spec_string("glb-file", "GLB File",
            "Path to a GLB 3D asset to load. When unset the built-in cube is used.",
            NULL,
            G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));

    gst_element_class_set_static_metadata(element_class,
        "FLUX Video Texture",
        "Filter/Effect/Video",
        "Uploads RGBA video frames as GPU textures onto a Filament 3D scene "
        "(FLUX Protocol Spec v0.6.3 §16 — fluxvideotex)",
        "FLUX Project");

    gst_element_class_add_static_pad_template(element_class, &sink_template);
    gst_element_class_add_static_pad_template(element_class, &src_template);

    bt_class->transform_caps = flux_videotex_transform_caps;
    bt_class->set_caps        = flux_videotex_set_caps;
    bt_class->get_unit_size   = flux_videotex_get_unit_size;
    bt_class->transform       = flux_videotex_transform;
    bt_class->passthrough_on_same_caps = FALSE;
}

/* ── Instance init ───────────────────────────────────────────────────────── */
static void flux_videotex_init(FluxVideotex* self)
{
    self->out_width   = 1280;
    self->out_height  = 720;
    self->period_x    = 150.0;
    self->period_y    = 200.0;
    self->period_z    = 300.0;
    self->color_space  = FLUX_CS_SRGB;
    self->ycbcr_output = FALSE;
    self->glb_file    = NULL;
    self->scene       = NULL;
    self->start_ns    = GST_CLOCK_TIME_NONE;
}

/* ── Property accessors ──────────────────────────────────────────────────── */
static void flux_videotex_set_property(GObject* object, guint prop_id,
                                       const GValue* value, GParamSpec* pspec)
{
    FluxVideotex* self = FLUX_VIDEOTEX(object);
    switch (prop_id) {
    case PROP_WIDTH:        self->out_width    = g_value_get_uint(value);   break;
    case PROP_HEIGHT:       self->out_height   = g_value_get_uint(value);   break;
    case PROP_PERIOD_X:     self->period_x     = g_value_get_double(value); break;
    case PROP_PERIOD_Y:     self->period_y     = g_value_get_double(value); break;
    case PROP_PERIOD_Z:     self->period_z     = g_value_get_double(value); break;
    case PROP_COLOR_SPACE:
        self->color_space = (FluxColorSpaceMode)g_value_get_enum(value);
        /* Re-create scene on next buffer so ColorGrading is rebuilt */
        if (self->scene) {
            filament_scene_destroy(self->scene);
            self->scene    = NULL;
            self->start_ns = GST_CLOCK_TIME_NONE;
        }
        break;
    case PROP_YCBCR_OUTPUT:
        self->ycbcr_output = g_value_get_boolean(value);
        if (self->scene) {
            filament_scene_destroy(self->scene);
            self->scene    = NULL;
            self->start_ns = GST_CLOCK_TIME_NONE;
        }
        break;
    case PROP_GLB_FILE:
        g_free(self->glb_file);
        self->glb_file = g_value_dup_string(value);
        if (self->scene) {
            filament_scene_destroy(self->scene);
            self->scene    = NULL;
            self->start_ns = GST_CLOCK_TIME_NONE;
        }
        break;
    default: G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec); break;
    }
}

static void flux_videotex_get_property(GObject* object, guint prop_id,
                                       GValue* value, GParamSpec* pspec)
{
    FluxVideotex* self = FLUX_VIDEOTEX(object);
    switch (prop_id) {
    case PROP_WIDTH:        g_value_set_uint(value,    self->out_width);    break;
    case PROP_HEIGHT:       g_value_set_uint(value,    self->out_height);   break;
    case PROP_PERIOD_X:     g_value_set_double(value,  self->period_x);     break;
    case PROP_PERIOD_Y:     g_value_set_double(value,  self->period_y);     break;
    case PROP_PERIOD_Z:     g_value_set_double(value,  self->period_z);     break;
    case PROP_COLOR_SPACE:  g_value_set_enum(value,    self->color_space);  break;
    case PROP_YCBCR_OUTPUT: g_value_set_boolean(value, self->ycbcr_output); break;
    case PROP_GLB_FILE:     g_value_set_string(value,  self->glb_file);     break;
    default: G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec); break;
    }
}

/* ── Finalize ────────────────────────────────────────────────────────────── */
static void flux_videotex_finalize(GObject* object)
{
    FluxVideotex* self = FLUX_VIDEOTEX(object);
    if (self->scene) {
        filament_scene_destroy(self->scene);
        self->scene = NULL;
    }
    g_free(self->glb_file);
    self->glb_file = NULL;
    G_OBJECT_CLASS(parent_class)->finalize(object);
}

/* ── Caps transform: sink caps → src caps (change width/height to out_w/h) ─ */
static GstCaps* flux_videotex_transform_caps(GstBaseTransform* trans,
                                              GstPadDirection direction,
                                              GstCaps* caps,
                                              GstCaps* filter)
{
    FluxVideotex* self = FLUX_VIDEOTEX(trans);
    GstCaps* result;

    if (direction == GST_PAD_SINK) {
        /* Sink→Src: fix output size and format to our render dimensions.
         * When ycbcr_output is TRUE the ColorGrading LUT stores Y'CbCr in
         * the RGBA8 buffer (R=Y', G=Cb, B=Cr, A=1), so we advertise AYUV
         * downstream; otherwise plain RGBA. */
        const char* fmt = self->ycbcr_output ? "AYUV" : "RGBA";
        result = gst_caps_new_simple("video/x-raw",
            "format",    G_TYPE_STRING, fmt,
            "width",     G_TYPE_INT,    (gint)self->out_width,
            "height",    G_TYPE_INT,    (gint)self->out_height,
            "framerate", GST_TYPE_FRACTION_RANGE, 0, 1, G_MAXINT, 1,
            NULL);
    } else {
        /* Src→Sink: passthrough; accept any RGBA input */
        result = gst_caps_new_simple("video/x-raw",
            "format", G_TYPE_STRING, "RGBA",
            NULL);
    }

    if (filter) {
        GstCaps* tmp = gst_caps_intersect_full(filter, result,
                                               GST_CAPS_INTERSECT_FIRST);
        gst_caps_unref(result);
        result = tmp;
    }
    return result;
}

/* ── set_caps: called when caps are negotiated ───────────────────────────── */
static gboolean flux_videotex_set_caps(GstBaseTransform* trans,
                                        GstCaps* incaps, GstCaps* outcaps)
{
    (void)incaps; (void)outcaps;
    FluxVideotex* self = FLUX_VIDEOTEX(trans);

    /* Tear down any existing scene so it is re-created on next buffer */
    if (self->scene) {
        filament_scene_destroy(self->scene);
        self->scene  = NULL;
        self->start_ns = GST_CLOCK_TIME_NONE;
    }
    return TRUE;
}

/* ── get_unit_size: bytes per frame for each caps ────────────────────────── */
static gboolean flux_videotex_get_unit_size(GstBaseTransform* trans,
                                             GstCaps* caps, gsize* size)
{
    GstVideoInfo info;
    if (!gst_video_info_from_caps(&info, caps))
        return FALSE;
    *size = (gsize)GST_VIDEO_INFO_SIZE(&info);
    return TRUE;
}

/* ── transform: core processing ──────────────────────────────────────────── */
static GstFlowReturn flux_videotex_transform(GstBaseTransform* trans,
                                              GstBuffer* inbuf,
                                              GstBuffer* outbuf)
{
    FluxVideotex* self = FLUX_VIDEOTEX(trans);

    /* ── Lazy-init Filament scene ───────────────────────────────────── */
    if (!self->scene) {
        const uint8_t* glb_data = cube_glb;
        size_t         glb_size = cube_glb_len;
        uint8_t*       glb_buf  = NULL;

        /* Load from file if glb-file property is set */
        if (self->glb_file && self->glb_file[0] != '\0') {
            FILE* f = fopen(self->glb_file, "rb");
            if (!f) {
                GST_ERROR_OBJECT(self, "cannot open glb-file: %s", self->glb_file);
                return GST_FLOW_ERROR;
            }
            fseek(f, 0, SEEK_END);
            long sz = ftell(f);
            rewind(f);
            if (sz <= 0) {
                GST_ERROR_OBJECT(self, "glb-file is empty: %s", self->glb_file);
                fclose(f);
                return GST_FLOW_ERROR;
            }
            glb_buf = (uint8_t*)malloc((size_t)sz);
            if (!glb_buf || fread(glb_buf, 1, (size_t)sz, f) != (size_t)sz) {
                GST_ERROR_OBJECT(self, "failed to read glb-file: %s", self->glb_file);
                free(glb_buf);
                fclose(f);
                return GST_FLOW_ERROR;
            }
            fclose(f);
            glb_data = glb_buf;
            glb_size = (size_t)sz;
            GST_INFO_OBJECT(self, "loaded GLB from file: %s (%zu bytes)",
                            self->glb_file, glb_size);
        }

        self->scene = filament_scene_create(
            (int)self->out_width, (int)self->out_height,
            glb_data, glb_size,
            (int)self->color_space,
            (int)self->ycbcr_output);

        free(glb_buf);   /* safe to free — Filament has parsed it by now */

        if (!self->scene) {
            GST_ERROR_OBJECT(self, "filament_scene_create failed");
            return GST_FLOW_ERROR;
        }
        self->start_ns = GST_CLOCK_TIME_NONE;
    }

    /* ── Elapsed time ───────────────────────────────────────────────── */
    GstClockTime pts = GST_BUFFER_PTS(inbuf);
    if (!GST_CLOCK_TIME_IS_VALID(pts))
        pts = GST_BUFFER_DTS(inbuf);

    gint64 now_ns;
    if (GST_CLOCK_TIME_IS_VALID(pts)) {
        if (self->start_ns == (gint64)GST_CLOCK_TIME_NONE)
            self->start_ns = (gint64)pts;
        now_ns = (gint64)pts - self->start_ns;
    } else {
        now_ns = 0;
    }
    double elapsed_s = (double)now_ns / 1e9;

    /* ── Map input buffer ───────────────────────────────────────────── */
    GstVideoInfo in_info;
    GstCaps* sink_caps = gst_pad_get_current_caps(GST_BASE_TRANSFORM_SINK_PAD(trans));
    if (!sink_caps || !gst_video_info_from_caps(&in_info, sink_caps)) {
        if (sink_caps) gst_caps_unref(sink_caps);
        GST_ERROR_OBJECT(self, "could not get sink caps");
        return GST_FLOW_ERROR;
    }
    gst_caps_unref(sink_caps);

    GstMapInfo in_map;
    if (!gst_buffer_map(inbuf, &in_map, GST_MAP_READ)) {
        GST_ERROR_OBJECT(self, "failed to map input buffer");
        return GST_FLOW_ERROR;
    }

    /* ── Map output buffer ──────────────────────────────────────────── */
    GstMapInfo out_map;
    if (!gst_buffer_map(outbuf, &out_map, GST_MAP_WRITE)) {
        gst_buffer_unmap(inbuf, &in_map);
        GST_ERROR_OBJECT(self, "failed to map output buffer");
        return GST_FLOW_ERROR;
    }

    /* ── Render ─────────────────────────────────────────────────────── */
    filament_scene_render(self->scene,
                          in_map.data,
                          GST_VIDEO_INFO_WIDTH(&in_info),
                          GST_VIDEO_INFO_HEIGHT(&in_info),
                          elapsed_s,
                          self->period_x,
                          self->period_y,
                          self->period_z,
                          out_map.data);

    gst_buffer_unmap(outbuf, &out_map);
    gst_buffer_unmap(inbuf,  &in_map);

    /* Copy PTS/DTS/duration to output buffer */
    GST_BUFFER_PTS(outbuf)      = GST_BUFFER_PTS(inbuf);
    GST_BUFFER_DTS(outbuf)      = GST_BUFFER_DTS(inbuf);
    GST_BUFFER_DURATION(outbuf) = GST_BUFFER_DURATION(inbuf);

    return GST_FLOW_OK;
}

/* ── Plugin registration ─────────────────────────────────────────────────── */
gboolean flux_videotex_register(GstPlugin* plugin)
{
    return gst_element_register(plugin, "fluxvideotex",
                                GST_RANK_NONE,
                                FLUX_TYPE_VIDEOTEX);
}

static gboolean plugin_init(GstPlugin* plugin)
{
    return flux_videotex_register(plugin);
}

GST_PLUGIN_DEFINE(
    GST_VERSION_MAJOR,
    GST_VERSION_MINOR,
    fluxvideotex,
    "FLUX video-texture element (§16 fluxvideotex) — renders RGBA video "
    "onto a Filament 3D scene with multi-axis rotation",
    plugin_init,
    "0.1.0",
    "BSD-3-Clause",
    "gst-fluxvideotex",
    "https://github.com/jesusluque/flux"
)
